# Generated by Django 3.2.4 on 2021-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('Class Nursery', 'Class Nursery'), ('Class LKG', 'Class LKG'), ('Class PRE KG', 'Class PRE KG'), ('Class UKG', 'Class UKG'), ('Class I', 'Class I'), ('Class II', 'Class II'), ('Class III', 'Class III'), ('Class IV', 'Class IV'), ('Class V', 'Class V'), ('Class VI', 'Class VI'), ('Class VII', 'Class VII'), ('Class VIII', 'Class VIII'), ('Class IX', 'Class IX'), ('Class X', 'Class X'), ('Class XI', 'Class XI'), ('Class XII', 'Class XII')], max_length=100, null=True)),
                ('fee_type', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half yearly', 'Half yearly'), ('annually', 'Annually')], max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='admission_period',
        ),
        migrations.AlterField(
            model_name='school',
            name='grades_end',
            field=models.CharField(choices=[('Class Nursery', 'Class Nursery'), ('Class LKG', 'Class LKG'), ('Class PRE KG', 'Class PRE KG'), ('Class UKG', 'Class UKG'), ('Class I', 'Class I'), ('Class II', 'Class II'), ('Class III', 'Class III'), ('Class IV', 'Class IV'), ('Class V', 'Class V'), ('Class VI', 'Class VI'), ('Class VII', 'Class VII'), ('Class VIII', 'Class VIII'), ('Class IX', 'Class IX'), ('Class X', 'Class X'), ('Class XI', 'Class XI'), ('Class XII', 'Class XII')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='grades_start',
            field=models.CharField(choices=[('Class Nursery', 'Class Nursery'), ('Class LKG', 'Class LKG'), ('Class PRE KG', 'Class PRE KG'), ('Class UKG', 'Class UKG'), ('Class I', 'Class I'), ('Class II', 'Class II'), ('Class III', 'Class III'), ('Class IV', 'Class IV'), ('Class V', 'Class V'), ('Class VI', 'Class VI'), ('Class VII', 'Class VII'), ('Class VIII', 'Class VIII'), ('Class IX', 'Class IX'), ('Class X', 'Class X'), ('Class XI', 'Class XI'), ('Class XII', 'Class XII')], max_length=50, null=True),
        ),
    ]
