# Generated by Django 3.2.4 on 2021-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20210623_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
