# Generated by Django 3.2.4 on 2021-06-26 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20210623_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.school'),
        ),
    ]
